export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const CHANGE_THEME = "ASYNC_INCREMENT";
export const DISABLE_BUTTONS = "DISABLE_BUTTONS";
export const ENABLE_BUTTONS = "ENABLE_BUTTONS";

